name: crimegraph
dependencies:
- python=3.10
- numpy
- pandas
- seaborn
- tensorflow
- scikit-learn
- jupyterlab
- pip
- networkx
- python-louvain
- jupyter
- pyogrio
- conda-forge::shapely
- conda-forge::libtiff
- conda-forge::geopandas
- conda-forge::matplotlib