<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mike Subelsky">
<meta name="dcterms.date" content="2024-01-27">
<meta name="keywords" content="graph deep learning, gis, gldNET, crime forecasting, machine learning">

<title>CrimeGraph: Model Development</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="model_development_files/libs/clipboard/clipboard.min.js"></script>
<script src="model_development_files/libs/quarto-html/quarto.js"></script>
<script src="model_development_files/libs/quarto-html/popper.min.js"></script>
<script src="model_development_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="model_development_files/libs/quarto-html/anchor.min.js"></script>
<link href="model_development_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="model_development_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="model_development_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="model_development_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="model_development_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@700&amp;display=swap" rel="stylesheet">

<style>
    #header {
        background-color: #070707; /* Rich Black FOGRA 39 */
        font-family: 'Orbitron', 'Arial', sans-serif;
    }

    #header a {
        color: #b7fdfe;
    }

    #header ul.dropdown-menu {
        background-color: #070707;
    }

    #header a.disabled {
        color: #b7fdfe;
        opacity: 0.5;
    }
</style>
</head><body><ul class="nav justify-content-center" id="header">
  <li class="nav-item">
    <a class="nav-link" href="/crimegraph">
      Home
    </a>
  </li>

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Chapters</a>
    <ul class="dropdown-menu">
      <li><a class="dropdown-item" href="../street_graph_feature_engineering">Part 1</a></li>
      <li><a class="dropdown-item" href="../event_timestep_feature_engineering/">Part 2</a></li>
      <li><a class="dropdown-item active" aria-current="page" aria-disabled="true" href="#">Part 3</a></li>
      <li><hr class="dropdown-divider"></li>
      <li><a class="dropdown-item disabled" aria-disabled="true" href="#">Part 4 (coming soon)</a></li>
    </ul>
  </li>
</ul>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>






<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#load-street-graph-and-crime-events" id="toc-load-street-graph-and-crime-events" class="nav-link" data-scroll-target="#load-street-graph-and-crime-events"><span class="header-section-number">1</span> Load Street Graph and Crime Events</a></li>
  <li><a href="#create-data-tensor" id="toc-create-data-tensor" class="nav-link" data-scroll-target="#create-data-tensor"><span class="header-section-number">2</span> Create Data Tensor</a></li>
  <li><a href="#establish-important-hyperparameters" id="toc-establish-important-hyperparameters" class="nav-link" data-scroll-target="#establish-important-hyperparameters"><span class="header-section-number">3</span> Establish Important Hyperparameters</a></li>
  <li><a href="#create-training-validation-and-test-sets" id="toc-create-training-validation-and-test-sets" class="nav-link" data-scroll-target="#create-training-validation-and-test-sets"><span class="header-section-number">4</span> Create Training, Validation, and Test Sets</a></li>
  <li><a href="#create-metrics" id="toc-create-metrics" class="nav-link" data-scroll-target="#create-metrics"><span class="header-section-number">5</span> Create Metrics</a></li>
  <li><a href="#create-a-baseline-model" id="toc-create-a-baseline-model" class="nav-link" data-scroll-target="#create-a-baseline-model"><span class="header-section-number">6</span> Create a Baseline Model</a></li>
  <li><a href="#create-the-gldnet-model" id="toc-create-the-gldnet-model" class="nav-link" data-scroll-target="#create-the-gldnet-model"><span class="header-section-number">7</span> Create the GLDNet Model</a></li>
  <li><a href="#train-the-gldnet-model" id="toc-train-the-gldnet-model" class="nav-link" data-scroll-target="#train-the-gldnet-model"><span class="header-section-number">8</span> Train the GLDNet Model</a></li>
  <li><a href="#up-next" id="toc-up-next" class="nav-link" data-scroll-target="#up-next"><span class="header-section-number">9</span> Up Next</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">CrimeGraph: Model Development</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p><a href="https://www.subelsky.com">Mike Subelsky</a> </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 27, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="introduction">Introduction</h2>
<p>In <a href="https://www.subelsky.com/crimegraph/street_graph_feature_engineering/">part 1</a> and <a href="https://www.subelsky.com/crimegraph/event_timestep_feature_engineering/">part 2</a> of the CrimeGraph project, we performed feature engineering on the spatial and temporal data of the <a href="https://spotcrime.com/">SpotCrime</a> crime event dataset.</p>
<p>In part 3, we will build the first version of a graph neural network model and train it to make rudimentary predictions for the risk of violent crime events. We are using the GLDNet<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> architecture described in the 2020 paper <em><a href="https://discovery.ucl.ac.uk/id/eprint/10085742/">Graph Deep Learning Model for Network-based Predictive Hotspot Mapping of Sparse Spatio-Temporal Events</a></em>.</p>
<p>The source code is available on <a href="https://github.com/subelsky/crimegraph">GitHub</a>.</p>
</section>
<section id="load-street-graph-and-crime-events" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="load-street-graph-and-crime-events"><span class="header-section-number">1</span> Load Street Graph and Crime Events</h2>
<p>We begin by loading the street graph which stores each street segments as nodes. Intersections between segments are modeled as edges connecting nodes. Each edge has a <code>weight</code> representing the network strength of the relationship between streets. See <a href="https://www.subelsky.com/crimegraph/street_graph_feature_engineering/">part 1</a> for details.</p>
<div class="cell" data-execution_count="134">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pickle</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>file_path <span class="op">=</span> <span class="st">'../../data/processed/baltimore_street_graph.gpickle'</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(file_path, <span class="st">'rb'</span>) <span class="im">as</span> f:</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    G <span class="op">=</span> pickle.load(f)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Sample street nodes (first number is the NodeIndex used in the events dataframe):</span><span class="ch">\n</span><span class="st">'</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> node <span class="kw">in</span> <span class="bu">list</span>(G.nodes.data())[<span class="va">None</span>:<span class="dv">5</span>:<span class="va">None</span>]:</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(node)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Sample edges ('weight' is the network strength of the relationship between streets):</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> edge <span class="kw">in</span> <span class="bu">list</span>(G.edges.data())[<span class="va">None</span>:<span class="dv">5</span>:<span class="va">None</span>]:</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(edge)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Sample street nodes (first number is the NodeIndex used in the events dataframe):

(0, {'NodeID': 367225, 'name': 'N DUKELAND ST', 'position': (429023.8628222718, 181450.00684655222)})
(1, {'NodeID': 367456, 'name': 'W READ ST', 'position': (433112.90626279684, 181374.68178852845)})
(2, {'NodeID': 367483, 'name': 'REMINGTON AVE', 'position': (432440.1964178119, 184064.86845014035)})
(3, {'NodeID': 367488, 'name': 'CANTERBURY RD', 'position': (432716.56154741155, 185417.96152212998)})
(4, {'NodeID': 367592, 'name': 'SWEET AIR ST', 'position': (431223.7876548111, 184620.00943614714)})

Sample edges ('weight' is the network strength of the relationship between streets):

(0, 89, {'distance': 207.24859639546855, 'weight': 0.9625401124585142})
(0, 169, {'distance': 170.25866131463928, 'weight': 0.9745620176687882})
(0, 256, {'distance': 287.5199729004246, 'weight': 0.9291524699760467})
(0, 498, {'distance': 581.1777592139317, 'weight': 0.7406420337058561})
(0, 545, {'distance': 76.50819939674132, 'weight': 0.9948103975797566})</code></pre>
</div>
</div>
<p>Next, we load the crime event timesteps prepared in <a href="https://www.subelsky.com/crimegraph/event_timestep_feature_engineering/">part 2</a> by mapping each event to the nearest street segment node. <code>NodeIndex</code> refers to the position of the node in the street graph’s index.</p>
<p>The feature columns are named ’*SMOOTHED’ because the values for each timestep were exponentially smoothed across the preceding timesteps in part 2, to facilitate neural network training.</p>
<div class="cell" data-execution_count="135">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>file_path <span class="op">=</span> <span class="st">'../../data/processed/timesteps.csv.gz'</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the timesteps dataframe, ensuring that integer columns are read as integers</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>timesteps <span class="op">=</span> pd.read_csv(file_path, dtype<span class="op">=</span>{<span class="st">'NodeIndex'</span>: <span class="st">'int'</span>, <span class="st">'Arrest'</span>: <span class="st">'int'</span>, <span class="st">'Property'</span>: <span class="st">'int'</span>, <span class="st">'Violent'</span>: <span class="st">'int'</span>})</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Groups the timesteps by date and node index so we can construct a tensor representing timesteps x num_nodes x features</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>timesteps.reset_index(inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>timesteps.set_index([<span class="st">'Date'</span>, <span class="st">'NodeIndex'</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Exclude the columns 'Arrest' and 'Property' for now, although we may want to use them later</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co"># if we experiment with new exponential smoothing factors during hyperparameter tuning</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>feature_columns <span class="op">=</span> [<span class="st">'ArrestSmoothed'</span>, <span class="st">'PropertySmoothed'</span>, <span class="st">'ViolentSmoothed'</span>]</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co"># The label column is what we want the model to predict, one day in the future</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>label_column <span class="op">=</span> <span class="st">'Violent'</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter the timesteps DataFrame to keep only the feature columns and label</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>timesteps <span class="op">=</span> timesteps[feature_columns <span class="op">+</span> [label_column]]</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>timesteps.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="135">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ArrestSmoothed</th>
<th data-quarto-table-cell-role="th">PropertySmoothed</th>
<th data-quarto-table-cell-role="th">ViolentSmoothed</th>
<th data-quarto-table-cell-role="th">Violent</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th">NodeIndex</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td rowspan="5" data-quarto-table-cell-role="th" data-valign="top">2015-01-01</td>
<td data-quarto-table-cell-role="th">0</td>
<td>0.0</td>
<td>0.0</td>
<td>2.0</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">27</td>
<td>0.0</td>
<td>0.0</td>
<td>1.0</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">36</td>
<td>0.0</td>
<td>1.0</td>
<td>0.0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">44</td>
<td>0.0</td>
<td>1.0</td>
<td>1.0</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">53</td>
<td>1.0</td>
<td>0.0</td>
<td>0.0</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>In order to save computation time and memory, a subset of crime events was selected across a representative swath of Baltimore neighborhoods:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="baltimore_event_subset.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">City of Baltimore overlaid with crime event subset</figcaption>
</figure>
</div>
</section>
<section id="create-data-tensor" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="create-data-tensor"><span class="header-section-number">2</span> Create Data Tensor</h2>
<p>We can now unify the spatial and temporal data into a single object suitable for training a neural network: a <em>tensor</em>.</p>
<p>ChatGPT gave me a pretty good general purpose definition of tensor:</p>
<blockquote class="blockquote">
<p>“…a mathematical way to represent a collection of numbers that might have various layers of depth. A single number is called a scalar, a list of numbers is a vector (like a row or column in a spreadsheet), and a grid of numbers is a matrix (like a whole spreadsheet).</p>
</blockquote>
<blockquote class="blockquote">
<p>A tensor extends this idea to even more dimensions, allowing for a more comprehensive representation of information, which is essential in tasks like image recognition or language processing in machine learning.”</p>
</blockquote>
<div class="cell" data-execution_count="136">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> lib.data <span class="im">import</span> create_data_tensor</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>num_nodes <span class="op">=</span> G.number_of_nodes()</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>data_tensor <span class="op">=</span> create_data_tensor(timesteps, num_nodes, feature_columns)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="137">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Shape of data tensor: </span><span class="sc">{</span>data_tensor<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Number of days: </span><span class="sc">{</span>data_tensor<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Number of nodes: </span><span class="sc">{</span>data_tensor<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Number of channels per node: </span><span class="sc">{</span>data_tensor<span class="sc">.</span>shape[<span class="dv">2</span>]<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Shape of data tensor: (3232, 1177, 4)
Number of days: 3232
Number of nodes: 1177
Number of channels per node: 4</code></pre>
</div>
</div>
<p><code>data_tensor</code> now contains a 3D tensor with shape <code>(timesteps, nodes, features)</code>:</p>
<p>For each of the <code>3232</code> days in the timesteps dataset:</p>
<ul>
<li><p>There are <code>1177</code> feature vectors, one for each of the <code>1177</code> street segment nodes</p></li>
<li><p>Each feature vector contains <code>3</code> numerical features (<code>ArrestSmoothed</code>, <code>PropertySmoothed</code>, and <code>ViolentSmoothed</code>).</p></li>
<li><p>Each feature vector contains <code>1</code> additional channel, <code>Violent</code>: the non-smoothed violent crime count for each node. <code>Violent</code> is the target variable for the model, known as the <em>label</em>. For any given date at a given node, <code>Violent</code> is the number of violent crimes that should have been predicted for that node on that date.</p></li>
</ul>
</section>
<section id="establish-important-hyperparameters" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="establish-important-hyperparameters"><span class="header-section-number">3</span> Establish Important Hyperparameters</h2>
<p>There are many hyperparameters that can be tuned to improve the performance of a neural network. We start with a few that are important to the GLDNet architecture. These initial default values were chosen based on the ones used in the original paper:</p>
<div class="cell" data-execution_count="138">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Deep learning models typically train with several examples at a time, called a batch</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>batch_size <span class="op">=</span> <span class="dv">16</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Governs the misprediction cost for nodes with zero violent crimes</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>loss_rho <span class="op">=</span> <span class="fl">0.03</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Used to calculate "hit rate" accuracy, by scoring predictions from the top 20% of street segments</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>hit_rate_coverage <span class="op">=</span> <span class="fl">0.2</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Defines the number of times the model will see each example during training</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>epochs <span class="op">=</span> <span class="dv">15</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="create-training-validation-and-test-sets" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="create-training-validation-and-test-sets"><span class="header-section-number">4</span> Create Training, Validation, and Test Sets</h2>
<p>To prevent the model from simply memorizing the training data (known as ‘overfitting’), we create three data sets:</p>
<ul>
<li><code>training_data</code>: used to train the model (70%)</li>
<li><code>validation_data</code>: used to evaluate performance during training (10%)</li>
<li><code>test_data</code>: used to evaluate the final performance of the model (20%)</li>
</ul>
<p>Because the model only learns from <code>training_data</code>, we use the remaining 30% to keep the model honest. Since this is a time forecasting problem, we use the newest events for evaluation: temporal patterns can change over time, and we want near-term predictions to use the most recent events for inference.</p>
<div class="cell" data-execution_count="139">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> lib.data <span class="im">import</span> create_dataset</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>total_windows <span class="op">=</span> data_tensor.shape[<span class="dv">0</span>]</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>training_window_size <span class="op">=</span> <span class="bu">int</span>(<span class="fl">0.7</span> <span class="op">*</span> total_windows)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>validation_window_size <span class="op">=</span> <span class="bu">int</span>(<span class="fl">0.10</span> <span class="op">*</span> total_windows)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the first 70% of the data for training</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>training_slice <span class="op">=</span> data_tensor[:training_window_size]</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>training_data <span class="op">=</span> create_dataset(training_slice)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the next 10% for validation while training</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>validation_slice <span class="op">=</span> data_tensor[training_window_size:training_window_size <span class="op">+</span> validation_window_size]</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>validation_data <span class="op">=</span> create_dataset(validation_slice)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the remaining, most recent 20% of the data for testing after training is complete</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>test_data <span class="op">=</span> data_tensor[training_window_size <span class="op">+</span> validation_window_size:]</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>test_data <span class="op">=</span> create_dataset(test_data)</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Controls how well-shuffled the training data is before each epoch;</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a><span class="co"># since our dataset is relatively we small, we can afford to shuffle it completely,</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a><span class="co"># meaning the shuffle buffer size is equal to the number of examples in the training set</span></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>shuffle_buffer_size <span class="op">=</span> training_data.cardinality()</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Shuffles the training data so that the model sees examples in random order for every training epoch;</span></span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a><span class="co"># also batches the training data into groups of examples</span></span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>training_data <span class="op">=</span> training_data.shuffle(shuffle_buffer_size).batch(batch_size)</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Validation and test data do not need to be shuffled, but are still batched, because the model</span></span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a><span class="co"># will have been trained to handle batches of examples</span></span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>validation_data <span class="op">=</span> validation_data.batch(batch_size)</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>test_data <span class="op">=</span> test_data.batch(batch_size)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="create-metrics" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="create-metrics"><span class="header-section-number">5</span> Create Metrics</h2>
<p>We need a way to measure the performance of the model. Following the GLDnet paper, we will adopt “hit rate accuracy” as our metric. Hit rate compares the number of successful predictions against actual violent crime occurrences for the most active segments of a timestep (in this case, the 20% of street segments with the most violent crime events).</p>
<p>Zhang and Cheng explain the metric in their paper:</p>
<blockquote class="blockquote">
<p>To calculate the hit rate, we first compute the prediction on each street segment, and then sort all segments by the predicted values in descending order. The street segments are selected in the sorted order and the proportion of the events falling on those street segments is tallied. … the hit rate is computed at maximum 20% street length coverage and the mean of the hit rates over all consecutive testing days is used as the metric for predictive mapping assessment.</p>
</blockquote>
<div class="cell" data-execution_count="140">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> lib.metrics <span class="im">import</span> HitRateMetric</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>metrics <span class="op">=</span> [HitRateMetric(num_nodes, hit_rate_coverage)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="create-a-baseline-model" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="create-a-baseline-model"><span class="header-section-number">6</span> Create a Baseline Model</h2>
<p>The simplest possible model would predict that the number of violent crimes occurring tomorrow would equal the number of violent crimes occurring today. Such a model doesn’t learn from the data and cannot be trained. We will use this as a baseline for our GLDNet performance; any model we build has to beat this ‘naive’ model.</p>
<div class="cell" data-execution_count="141">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> lib.model <span class="im">import</span> build_naive_model</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> lib.training <span class="im">import</span> test_model</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>naive_model <span class="op">=</span> build_naive_model(metrics, loss_rho<span class="op">=</span>loss_rho)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>test_model(naive_model, test_data, batch_size, metrics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="141">
<pre><code>{'hit_rate': 0.33807498}</code></pre>
</div>
</div>
<p><code>0.34</code> seemed surprisingly high to me, but it probably reflects obvious patterns in the data. If crime is consistently concentrated in some areas, even a simple model like this could perform reasonably well.</p>
</section>
<section id="create-the-gldnet-model" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="create-the-gldnet-model"><span class="header-section-number">7</span> Create the GLDNet Model</h2>
<p>The GLDNet architecture combines two neural network components:</p>
<ul>
<li><p><strong>Gated Network</strong>: learns long-range temporal dependencies between events. The gate determines which features of the event data to emphasize or suppress. Gated networks perform better with sparse data like ours (where most nodes on any given timestep will have zero crimes) than other types of models.</p></li>
<li><p><strong>Localized Diffusion Network</strong>: learns spatial dependencies across the street graph. The network models how events in one location influence other locations by treating events as a diffusion process, whereby each event creates information that ‘diffuses’ from one node to another.</p></li>
</ul>
<p>A final, ‘Dense’ layer is added to the model, which learns to map the output of the Gated and Localized Diffusion networks into a single value for each node: the predicted number of violent crimes at that node in the next, future timestep.</p>
<p>The GLDNet paper contains a nice illustration of the entire system:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="model_development_files/figure-html/4ac7ae22-1-image.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure 5 from <em>Graph Deep Learning Model for Network-based Predictive Hotspot Mapping of Sparse Spatio-Temporal Events</em></figcaption>
</figure>
</div>
<div class="cell" data-execution_count="148">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> lib.model <span class="im">import</span> build_model</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> lib.create_adjacency_matrix <span class="im">import</span> create_adjacency_matrix</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># The adjacency matrix represents all of the weighted edges between nodes;</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># the LocalizedDiffusionNetwork uses these weights to learn network structure</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>adjacency_matrix <span class="op">=</span> create_adjacency_matrix(G)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> build_model(adjacency_matrix,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>                    metrics,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>                    loss_rho<span class="op">=</span>loss_rho,</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>                    num_gated_relu_layers<span class="op">=</span><span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="train-the-gldnet-model" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="train-the-gldnet-model"><span class="header-section-number">8</span> Train the GLDNet Model</h2>
<p>We now train the model with the <code>training_data</code> we built earlier and test it using <code>test_data</code>:</p>
<div class="cell" data-execution_count="149">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>training_history <span class="op">=</span> model.fit(training_data, epochs<span class="op">=</span>epochs, validation_data<span class="op">=</span>validation_data, verbose<span class="op">=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="150">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> lib.plots <span class="im">import</span> plot_loss_and_metrics</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>plot_loss_and_metrics(training_history.history, name<span class="op">=</span><span class="st">'GLDNet v0'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="model_development_files/figure-html/cell-12-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="151">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>test_model(model, test_data, batch_size, metrics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="151">
<pre><code>{'hit_rate': 0.2022182}</code></pre>
</div>
</div>
<p><code>0.20</code> hit rate accuracy is significantly worse than the baseline model. To improve accuracy, we’ll need to test many hyperparameter configurations that govern the training process, the complexity of the model, and how the model learns. The relatively flat loss curve above suggests that with these hyperparameters, the model is learning very little from the training data.</p>
<p>I experimented locally with the <code>rho</code> parameter (which affects how the loss function weighs the influence of nodes where <code>Violent</code> is <code>0</code>), and was able to get a more promising result by setting <code>rho = 0.3666666666666667</code>:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="training_small_subset_rho_0.3666666666666667.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">GLDNet Training History Early Result</figcaption>
</figure>
</div>
</section>
<section id="up-next" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="up-next"><span class="header-section-number">9</span> Up Next</h2>
<p>Now we have a working model, it’s time to build a robust pipeline to test many combinations of hyperparameters. Our goal will be to find the best model and best training process for predicting crime events.</p>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Gated Localized Diffusion<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section><section class="quarto-appendix-contents"><h2 class="anchored quarto-appendix-heading">Reuse</h2><div id="quarto-reuse" class="quarto-appendix-contents"><div>CC BY-NC-SA 4.0</div></div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>